# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  v:
    taskfile: "~/.config/task/Taskfile.vars.yml"
    optional: true
    internal: false
    flatten: false

# optional configurations (output, silent, method, run, etc.)

# vars: # Use only uppercase letters for variable names

# env: # followed or replaced by dotenv

tasks:
  # Use kebab case for task names

  default:
    cmds:
      - echo "This is {{.TASKFILE}} at v{{.TASK_VERSION}}"
      - task --list --sort alphanumeric -t {{.TASKFILE}}
    silent: true

  task:init:
    desc: alternative task --init
    summary: |
      see https://github.com/go-task/task/issues/2012
      This task is an alternative to `task --init`.
      maybe `task -g new`
    aliases:
      - new
    vars:
      EXPORT_FILE_NAME: taskfile.yaml
      MY_INIT_TASKFILE: https://raw.githubusercontent.com/officel/config_task/refs/heads/main/Taskfile.yml
    cmds:
      - curl -sSL {{.MY_INIT_TASKFILE}} --output {{.USER_WORKING_DIR}}/{{.EXPORT_FILE_NAME}}
      - echo "exported to {{.USER_WORKING_DIR}}/{{.EXPORT_FILE_NAME}}"
      # - cat {{.USER_WORKING_DIR}}/{{.EXPORT_FILE_NAME}}
