# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  task:
    taskfile: "~/.config/task/Taskfile.task.yml"
    optional: true
    internal: false
    flatten: false
    aliases:
      - t

  variables:
    taskfile: "~/.config/task/Taskfile.vars.yml"
    optional: true
    internal: false
    flatten: false
    aliases:
      - v

# optional configurations (output, silent, method, run, etc.)
silent: false

# vars: # Use only uppercase letters for variable names
vars:
  MY_NAME: ""

# env: # followed or replaced by dotenv
dotenv:
  - .env
  - .env.local

tasks:
  # Use kebab case for task names

  default:
    cmds:
      - echo "This is {{.TASKFILE}} at v{{.TASK_VERSION}}"
      - task --list --sort alphanumeric -t {{.TASKFILE}}
    silent: true

  hello:
    desc: Hello World by task
    aliases:
      - h
    cmds:
      - echo "Hello, {{.MY_NAME | default .USER}}! Welcome to Task v{{.TASK_VERSION}}"
    silent: true
