# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev/

version: '3'

includes:
  dist:
    taskfile: Taskfile.dist.yml
    optional: true
    internal: false
    flatten: false

# vars:

# env:

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort alphanumeric

  work:
    desc: Work
    aliases:
      - w
    cmds:
      - echo "{{.TASK}} {{.ALIAS}}"
